### ISSUE TITLE
SkyLightProbe produces NaN texels under certain conditions

### ISSUE THREAD

**Issue by shotamatsuda** [takram-design-engineering/three-geospatial#13]
Related to https://github.com/takram-design-engineering/three-geospatial/issues/7

**Comment by shotamatsuda** [comment]
Confirmed that some vertices of Google Photographic 3D Tiles have normals as zero vectors. I'd rather say this is a bug in TileCreasedNormalsPlugin, or normals aren’t natively supported by Google Photographic 3D Tiles. Keeping this issue open for the record.

**Comment by gkjohnson** [comment]
This is odd... I wrote the `toCreasedNormals` function so I'll take a look later. The only reason I can imagine this happening is if we have a degenerate triangle with all vertices at a single point - but in that case we shouldn't see the triangle rasterized to the screen.

From https://github.com/takram-design-engineering/three-geospatial/commit/2b93b01be25cd8ad9f4079a0d48f7e019ed56f8b - do you know how are NaNs making it into that shader? Is it downsampling normals? Or are NaN values making it into the color buffer due to a 0,0,0 normals?

**Comment by shotamatsuda** [comment]
That shader takes the color buffer from the render pass, and NaN values are in the color buffer. I suspect the source is [here](https://github.com/mrdoob/three.js/blob/r171/src/renderers/shaders/ShaderChunk/lights_pars_begin.glsl.js#L40), which invokes [this](https://github.com/mrdoob/three.js/blob/r171/src/renderers/shaders/ShaderChunk/common.glsl.js#L67).

> but in that case we shouldn't see the triangle rasterized to the screen

That’s true, now that you mention it…

**Comment by gkjohnson** [comment]
"Fixing up" these degenerate normals seems to fix the issue:

```js
for ( let i = 0, l = normal.count; i < l; i += 3 ) {

  v0.fromBufferAttribute( normal, i + 0 );
  v1.fromBufferAttribute( normal, i + 1 );
  v2.fromBufferAttribute( normal, i + 2 );
  if ( v0.length() < 0.5 || v1.length() < 0.5 || v2.length() < 0.5 ) {

    normal.setXYZ( i + 0, 0, 0, 1 );
    normal.setXYZ( i + 1, 0, 0, 1 );
    normal.setXYZ( i + 2, 0, 0, 1 );

  }

}
```

I took a look and it looks like 0, 0, 0 normals are only generated on triangles with an area of 0. Though the triangles are degenerate lines - ie two vertices are in an identical location and the third is offset. I'd think this would result in no pixels being rasterized but this doesn't seem to be the case - though there may be something else going on? `computeVertexNormals` results in the same issue while setting `material.flatShading` does not.

**Comment by gkjohnson** [comment]
An image of `0, 0, 0` normals being rasterized, highlighted in red by modifying a normal material 🤷 :

<img width="300" alt="image" src="https://github.com/user-attachments/assets/f5b1302e-0d80-4c51-9c02-c8889b5feccd">

**Comment by shotamatsuda** [comment]
Fixed in https://github.com/takram-design-engineering/three-geospatial/commit/7fd13501de0df68c4591e6a8aa0f5282852b1cbf
