### ISSUE TITLE
Bug(?): Changing cameras causes atmospheric rendering to disappear

### ISSUE THREAD

**Issue by gkjohnson** [takram-design-engineering/three-geospatial#17]
I was looking into transitioning between an orthographic camera and perspective camera and noticed that when swapping out the camera with the `set` function that all the atmosphere effects are lost. You can easily test this by adding the following effect to the demo which just replaces the camera with a new cloned instanced of the current camera:

```js
  const set = useThree(({ set }) => set);
  const get = useThree(({ get }) => get);
  useEffect( () => {
    setTimeout( () => {
      const { camera } = get();
      set({ camera: camera.clone() });
    }, 5000);
  }, []);
```

And a before and after shot:

<img src="https://github.com/user-attachments/assets/05607762-7a7c-4032-825a-87ddffe95911" height="300" /> <img src="https://github.com/user-attachments/assets/f874f7b0-ad3f-45ab-9117-b2534500a31b" height="300" />

I can try looking into it, as well, but I thought you might know since I'm still learning about r3f. Is this a limitation of r3f's effect composer?

**Comment by shotamatsuda** [comment]
Yes, I think the state change somehow affects the EffectComposer to trigger a re-render its passes, and they are in an incorrect order. I believe this is a limitation of R3F’s EffectComposer component.

Adding the active camera ID to the children’s key will address this:

```ts
<Fragment
  // Effects are order-dependant; we need to reconstruct the nodes.
  key={JSON.stringify({
    enabled,
    sun,
    sky,
    transmittance,
    inscatter,
    correctGeometricError,
    lensFlare,
    normal,
    depth,
    lut,
    camera: camera.id // Added
  })}
>
  ...
</Fragment>
```

I’m not sure if this is the simplest solution, though.

**Comment by gkjohnson** [comment]
Interesting - it does seem like a bug in r3f's EffectComposer. Unfortunately recreating all the passes is really slow but it looks like this happens specifically when passes are recreated causing the order to get out of sync. #18 is an attempt at fixing it which lets us use the camera transitions and the ortho camera from #15:

https://github.com/user-attachments/assets/25a785a8-87a8-4fdd-998c-39279cfa7046

https://github.com/user-attachments/assets/a5238d77-a20a-42d0-ae01-7e35f197bab4
