### ISSUE TITLE
AerialPerspective: Shadows not rendering with orthographic camera

### ISSUE THREAD

**Issue by gkjohnson** [takram-design-engineering/three-geospatial#21]
You might have mentioned this in #15 but I don't think I fully understood. When working on adding the toggle to the demo page I'm seeing that the scene doesn't seem to render shadows. See the same view before and after ortho toggle. Note the lack of shadows on the mountain: 

<img height="300" alt="image" src="https://github.com/user-attachments/assets/29f09bca-1a34-494b-af83-819258616bc4" /> 
 <img height="300" alt="image" src="https://github.com/user-attachments/assets/4d5dcad4-1f47-4e09-858f-8cbf7ded8dc6" />

And the normals before and after switching (from a different area, of course 😅):

<img height="300" alt="image" src="https://github.com/user-attachments/assets/516d13bc-7726-40df-a472-60c26688bfe5" /> <img height="300" alt="image" src="https://github.com/user-attachments/assets/bfe00084-5f8a-4a1d-b0c6-b2c630e9c091" />

It looks like this is due to the `correctGeometricError` function that interpolates normals as the camera zooms out, calculating the interpolation factor based on camera height. I'll look into some other ways of addressing this for an orthographic camera.

**Comment by shotamatsuda** [comment]
> It looks like this is due to the correctGeometricError function that interpolates normals as the camera zooms out, calculating the interpolation factor based on camera height

Ah, yes, it relies on the camera height, which indeed can cause issues with orthographic cameras. Turning off the `correctGeometricError` toggle restores the shading, but of course, geometric errors intersecting the atmosphere becomes visible when zoomed out.

I initally thought this could be considered a bug, but I think it depends on how the position of orthographic camera is managed. If it’s managed in a similar way to how near/far planes are for perspective cameras in `3d-tiles-renderer`, then this behavior should be fine (if I understand orthographic projection correctly). 

Adding some sort of translation to the camera height for orthograhic camera (based to `zoom`, for example) could likely introduce other issues when in different contexts. How do you think?

**Comment by gkjohnson** [comment]
I didn't really think of it as a bug - more just an unconsidered scenario since orthographic camera wasn't supported previously.

> Adding some sort of translation to the camera height for orthograhic camera (based to zoom, for example) could likely introduce other issues when in different contexts. How do you think?

Unfortunately I don't think it's all that feasible to position the ortho camera the same way as the perspective camera. I spent a long time trying to figure out how to get the ortho camera working with globe controls 😅 But I have a proposal for a change to support both cameras in #23. Basically rather than interpolating based on camera "height" the normals are interpolated based on the apparent distance to the globe (meaning the projected screen size of the globe).

That means the interpolation will interpolate correctly and therefore use shadows correctly even when using something like a really far away camera with a really narrow FoV (eg 1 or 2 degrees), which is used for the persp <> ortho transition animation.
