### ISSUE TITLE
Sky rendering is incorrect on mobile

### ISSUE THREAD

**Issue by gkjohnson** [takram-design-engineering/three-geospatial#25]
On my Samsung Galaxy S20 device - looks like the adjusted depth comparison from https://github.com/takram-design-engineering/three-geospatial/issues/3#issuecomment-2511657038 is not so fool-proof 😬 Maybe there's a better way to handle this? Is there a reason `DepthTextures` aren't used here which might make this easier? Maybe that's an `EffectComposer` limitation? I'll have to think through a solution more.

<img src="https://github.com/user-attachments/assets/c10eeaf8-1d07-49e3-95c4-c02eb5c90819" height="400"/>

**Comment by shotamatsuda** [comment]
Although I'm not familiar with `DepthTexture` (after seeting the [example](https://github.com/mrdoob/three.js/blob/master/examples/webgl_depth_texture.html)), isn’t it overwritten during post-processing renders? It seems `postprocessing` is working around this in the [pipeline redesign](https://github.com/pmndrs/postprocessing/issues/419), which might address it.

As for the epsilon, is 1e-7 too small? Will something closer to 1e-6 (matching what [common.glsl](https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderChunk/common.glsl.js#L7C20-L7C21) defines) resolve the issue?

**Comment by gkjohnson** [comment]
> As for the epsilon, is 1e-7 too small?

It must be - I'll try different values on my phone when I get a chance to see if anything fixes it. Or maybe another solution will come to mind.

**Comment by shotamatsuda** [comment]
Just to add, I tried comparing the view Z instead of the depth value, but it didn’t work well for some reason I’m not sure. Maybe I need to revisit it.

**Comment by gkjohnson** [comment]
Turns out this isn't a depth issue at all 🤷 - see #25. Gotta love inconsistent behavior between platforms 😅
