### ISSUE TITLE
Atmosphere: Questions about use / limitations

### ISSUE THREAD

**Issue by gkjohnson** [takram-design-engineering/three-geospatial#3]
I've gotten a basic variant of this working now with 3d-tiles-renderer and wanted to ask a couple questions about the implementation and things that don't seem to be working. Sorry if it's scattered!

1. I see that both the "Sky" and "Stars" components take `renderTargetCount` fields but this isn't documented anywhere. Is it needed? Is this something that can be defaulted to `2` so the user doesn't have to set it?

2. On initial installation and run I get an error seemingly related to pnpm and nx. If I delete the pnpm-lock.yml file everything works. Is it possible for the project to work with npm or pnpm?

3. I see that `EffectComposer` is also exported from `three-geospatial-effects` which seems redundant to r3f's EffectComposer. Is there a reason it's redundantly defined?

4. I see that `GlobeControls` does not draw the circle helper and WebGL throws an error when it's visible. It looks like this is related to MRT? Do you know what the cause is?

```
GL_INVALID_OPERATION: Active draw buffers with missing fragment shader outputs.
```

5. I see that the atmosphere rendering does not work without `logarithmicDepthBuffer` enabled. Is this a deliberate limitation? Is it possible to make it work without it? Enabling logarithmic depth buffer can affect performance since it adjusts depth in the fragment shader so it would be best to avoid it if possible.

6. When switching between "deferred" and "forward" rendering I see that the shadowed areas look black with forward rendering. Is there anything else that needs to be enabled to get the ambient light working correctly?

_edit: Possibly related to 6, I notice that when using MeshStandardMaterial, the `SkyLight`, and the `LensFlare` component that the screen flashes black. Maybe there's some conflicting state?_

Thanks again - I'll make a couple other issues for some other bugs / features I'm interested in to discuss. As I mentioned on Twitter I can try to help with some of this, as well.

**Comment by shotamatsuda** [comment]
Thanks for sharing your feedback! Here are some responses:

1. `renderTargetCount` is intentionally undocumented and meant for internal use within the project this repository is for. It makes fragment shaders output `0` to additional MRT targets if set to more than `1`.

2. I will look onto it. Do you install the repository itself? The main README lacks setup instructions. Note that `pnpm` is the package manager for this repository. I've seen deduping issues with `postprocessing` when using `yarn`, which might apply to `npm` as well.

3. The `EffectComposer` exported from `three-geospatial-effects` differs:
	1. It uses half-float normal buffer
	2. It relies on [`GeometryPass`](https://github.com/takram-design-engineering/three-geospatial/blob/main/packages/effects/src/GeometryPass.ts) instead of `RenderPass`, which ties to the purpose of `renderTargetCount`.

4. This is likely related to 1 and 3, and I haven’t notice this. The examples in storybook use the `EffectComposer` from `three-geospatial-effects`, but the material in `GlobeControls` doesn’t output additional render targets. I’ll change the stories to use `EffectComposer` from `@react-three/postprocessing` because G-Buffer is not used in these.

5. The atmosphere works without `logarithmicDepthBuffer`. Do you see specific issues when it’s disabled?

6. In "deferred" mode, sun and sky irradiance are calculated with per-pixel world position in AerialPerspectiveEffect. In "forward" mode, these values are calculated at a single point in the scene using a directional light and light probe. In [Basic](https://github.com/takram-design-engineering/three-geospatial/blob/main/storybook/src/atmosphere/Atmosphere-Basic.tsx) example, the sample point is located over 5000 meters above the terrain, which is large enough that the direct sunlight condition differs.

**Comment by gkjohnson** [comment]
> 1. renderTargetCount is intentionally undocumented and **meant for internal use within the project this repository is for**. It makes fragment shaders output 0 to additional MRT targets if set to more than 1.

The storybook examples use this which is why it seemed necessary? (see [here](https://github.com/takram-design-engineering/three-geospatial/blob/2f1dd0f30d1bd9247d04a6c0d9fd9ee361e82ff5/storybook/src/atmosphere/PhotorealisticTiles-Story.tsx#L206-L207)) From your explanation below it sounds like this can go away with a change to EffectComposer.

> 2. Do you install the repository itself?

Yeah I've forked and locally cloned the project, ran `npm install`, and then `npm run storybook`. Here's what's logged when running `npm run storybook -- --verbose`. In short it seems like nx is looking for `.modules.yaml` in node_modules since pnpm-lock.yml is present. This may really be something that should be reported to next.js, though:

<details>
<summary>log output</summary>

```
$ npm run storybook -- --verbose

> @three-geospatial/source@0.0.0 storybook
> nx storybook storybook --port=4400 --no-open --verbose

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the nx/js/dependencies-and-lockfile plugin.
    - pnpm-lock.yaml: Could not find ".modules.yaml" at "/Users/garrett/Desktop/git/three-geospatial/node_modules/.modules.yaml"
      Error: Could not find ".modules.yaml" at "/Users/garrett/Desktop/git/three-geospatial/node_modules/.modules.yaml"
          at loadPnpmHoistedDepsDefinition (/Users/garrett/Desktop/git/three-geospatial/node_modules/nx/src/plugins/js/lock-file/utils/pnpm-normalizer.js:40:15)
```
</details>

> 3. The EffectComposer exported from three-geospatial-effects differs:
> ...
> I’ll change the stories to use EffectComposer from @react-three/postprocessing because G-Buffer is not used in these.

Got it - I think I see whats going on now. I wonder if the new three.js nodes system will make it easier for this kind of stuff to automatically-reconfigure when multiple render targets are present. Also what is the G-Buffer pass being used for, then?

> 5. The atmosphere works without logarithmicDepthBuffer. Do you see specific issues when it’s disabled?

Yeah here's a screenshot of what I'm seeing with the logarithmic depth buffer enabled and disabled. It just requires changing "logarithmicDepthBuffer" to false:

<img height="250" alt="image" src="https://github.com/user-attachments/assets/c13f5d4d-a63e-4be1-b45e-111f15e339b4"> <img height="250" alt="image" src="https://github.com/user-attachments/assets/d1bdcca0-638a-479b-9b63-86245f68d23a">

> 6. ... the sample point is located over 5000 meters above the terrain, which is large enough that the direct sunlight condition differs.

I've moved the height down to where the buildings are to get a more appropriate sample but I'm still seeing that the shadows are basically black. Here are two images showing the the differences - left is with the deferred shading, right is with the `SkyLight` and `SunLight` components. The red ball represents the position of the sky light and sun light components (and presumably where the light sampling is done). If this is significantly different from what you expect I can create a new issue  with an example demonstrating it. It's very possible I'm doing something wrong, too.

<img height="250" alt="image" src="https://github.com/user-attachments/assets/3ae7b81f-4f39-4c87-ba67-31ef73bd059e"> <img height="250" alt="image" src="https://github.com/user-attachments/assets/8f2e6d97-7409-48f2-8b4d-a92952fbf7b5">

**Comment by shotamatsuda** [comment]
> Possibly related to 6, I notice that when using MeshStandardMaterial, the SkyLight, and the LensFlare component that the screen flashes black. Maybe there's some conflicting state?

I’ve reproduced that SkyLight and LensFlare cause screen flashes. I will take a look onto this.

>I've moved the height down to where the buildings are to get a more appropriate sample but I'm still seeing that the shadows are basically black. Here are two images showing the the differences - left is with the deferred shading, right is with the SkyLight and SunLight components. The red ball represents the position of the sky light and sun light components (and presumably where the light sampling is done). If this is significantly different from what you expect I can create a new issue with an example demonstrating it. It's very possible I'm doing something wrong, too.

Below is my results:

Left: AerialPerspective's `sunIrradiance` and `skyIrradiance`
Right: SkyLight and SunLight

<img src='https://github.com/user-attachments/assets/f43bf224-91c6-4d93-8136-0a7c0739d307' height='300' /> <img src='https://github.com/user-attachments/assets/656c3faf-5ffa-4550-8ea1-74d72abad138' height='300' />

My code is:
https://github.com/takram-design-engineering/three-geospatial/compare/issue/foward-photorealistic-tiles?expand=1

Does this match your code? Let me know if I missed anything that I should have clarified.

**Comment by shotamatsuda** [comment]
Regarding the non-logarithmic depth buffer, the aerial perspective shader discards pixels when the raw depth value is near 1. It seems the threshold is set too far from 1:
https://github.com/takram-design-engineering/three-geospatial/blob/main/packages/atmosphere/src/shaders/aerialPerspectiveEffect.frag#L88

Changing 0.9999 to something closer, like 0.9999999, resolves the issue. We could even compare equality to 1.0 if we assume the depth buffer format is R16F or similar.

Do you have any suggestions on handling this kind of situation? It seems like a common problem.

**Comment by shotamatsuda** [comment]
Yes, the more I develop, the more I realize I should have started with TSL...

>Are you doing anything special to render unlit or reflective materials unaffected by the atmosphere in your work?

Sorry, could you clarify for me what you mean by unlit or reflective materials?

>What's the reason to not just compare with > 1.0? Is there a situation where we'd see precision issues around 1.0? From the three.js [DepthTexture documentation](https://threejs.org/docs/?q=depth#api/en/textures/DepthTexture.type) the possible depth types are 16, 24, or 32 bits.

Since AerialPerpespectiveEffect is a [postprocessing](https://github.com/pmndrs/postprocessing)’s effect, the depth buffer comes from [DepthPass](https://github.com/pmndrs/postprocessing/blob/main/src/passes/DepthPass.js), and MeshDepthMaterial packs the depths into EffectComposer's render buffer. Comparing it with `> 1.0` doesn’t work in this case.

>Thanks for taking a look at this stuff so quickly!

Probably just for now! 😊

**Comment by gkjohnson** [comment]
> Sorry, could you clarify for me what you mean by unlit or reflective materials?

Typically I might use an unlit material for a data visualization - eg an unlit cylinder or line for a path or unlit spheres for points of interest or something. But when using the "deferred" approach (which provides the more correct lighting) these unlit surfaces will be rendered with lighting (this is an unlit, mesh basic material sphere):

<img width="350" alt="image" src="https://github.com/user-attachments/assets/8f148bfe-8c84-4b74-bff4-8d15a2610a3b">

Likewise if we have objects that are specular or reflective (like windows) that should glint from the sun, the deferred path will not work since lighting is calculated using a lambertian model for lighting surfaces (as noted [here](https://github.com/takram-design-engineering/three-geospatial/tree/main/packages/atmosphere#deferred-lighting)). I can figure out how to make this work on my own, as well, but if you already have something you've worked out that would be great to know.

> Comparing it with `> 1.0` doesn’t work in this case.

Sorry I'd mistyped - I meant checking for `>= 1.0` which works on my machine. But I see there's a bit more to it -

> MeshDepthMaterial packs the depths into EffectComposer's render buffer. Comparing it with > 1.0 doesn’t work in this case.

Oh interesting... I see unpacking the RGBA happens [here](https://github.com/mrdoob/three.js/blob/3716f3ea7ce57c191d42769936da3355ae2c6908/src/renderers/shaders/ShaderChunk/packing.glsl.js#L56-L58) which does some floating point path even when the packed values are all `1`. I think it's hard to pick an epsilon in cases like this since different hardware may have different precision it's doing these operations in.

On my machine, though, I don't see a visual difference between a 1e-6 and 1e-7 epsilon for checking that depth. So setting it to one those values might be safe until there's an issue:

```glsl
if (depth >= 1.0 - 1e-7) {

  // ...

}
```

**Comment by shotamatsuda** [comment]
Now I see. No, I’ve realized that supporting mixed BRDFs *as a generic library* with GLSL is too complex. That’s why I created directional light and light probe to approximate it, instead of defining my own G-Buffer and deferred pass, hoping TSL might offer the flexibility to handle this (honestly, I don’t know much about node materials yet).

As a side note, I'm planning to fade between "forward" and "deferred" mode depending on the viewpoint, with the addition of a sea reflectance model (and perhaps a selective shading mask) built into the postprocessing pass, because from a distant view, most scene objects can be considered Lambertian, except for the ocean.

>On my machine, though, I don't see a visual difference between a 1e-6 and 1e-7 epsilon for checking that depth. So setting it to one those values might be safe until there's an issue:

Thank you, I’ll choose a similar epsilon for now. Thanks again for pointing out the issue.

**Comment by shotamatsuda** [comment]
Resolved 5. in https://github.com/takram-design-engineering/three-geospatial/commit/06e208f4267d0879eb10a101017800e121f4ac4d

**Comment by shotamatsuda** [comment]
Resolved 1. 3. 4. in https://github.com/takram-design-engineering/three-geospatial/commit/e6e5f0cc9f7c29c3cd5f50941937804f32ee534b

**Comment by gkjohnson** [comment]
> (honestly, I don’t know much about node materials yet).

I don't either - it still feels like it's maturing. I'll dive into it some day. But I have high hopes.

> I'm planning to fade between "forward" and "deferred" mode depending on the viewpoint,

This is what I was thinking, as well.

> Resolved 1. 3. 4. in https://github.com/takram-design-engineering/three-geospatial/commit/e6e5f0cc9f7c29c3cd5f50941937804f32ee534b

And the changes look good! My only question is are there any benefits you're seeing by using a half float normal pass rather than a full float buffer beyond memory usage. Or better are there any downsides to the half float buffer? I'm wondering if this is change that would be good to make upstream to the r3f repo at some point.

**Comment by shotamatsuda** [comment]
Compared to full float, I haven’t seen any differences performance and quality-wise in half-float normal buffer.

**Comment by gkjohnson** [comment]
Thanks! I think this answers most everything for now. One drawback to the native "EffectComposer" and not using "GeometryPass" is that the tiles fade plugin doesn't work quite as well because the separate "NormalPass" doesn't respect the dither effect - and of course performance will be affected. A custom normal pass could help with this, though. I'll have think through it more.

**Comment by shotamatsuda** [comment]
I hadn’t noticed that, but no, normal materials aren’t patched and don’t fade now. I’ll look into it as well.
