### ISSUE TITLE
Atmosphere: Add support for "OrthographicCamera"

### ISSUE THREAD

**Issue by gkjohnson** [takram-design-engineering/three-geospatial#4]
Currently when rendering with an orthographic camera the atmosphere doesn't look right. It would be great to support an orthographic camera, as well. Are there any inherent limitations with the current approach that would prevent it from working?

You can recreate this by adding the `orthographic` property to the `<Canvas>` component.

<img width="300" alt="image" src="https://github.com/user-attachments/assets/35a0d8a6-e7fd-4f9b-9d8e-5f24acea4798">

_edit: It looks like this is probably (in part) caused by the assumption that the camera position is the view ray origin in the [fragment shaders](https://github.com/takram-design-engineering/three-geospatial/blob/2f1dd0f30d1bd9247d04a6c0d9fd9ee361e82ff5/packages/atmosphere/src/shaders/sky.vert#L13-L17). Instead we could probably using the inverse projection matrix to determine the ray origin at the near clip plane. Let me know what you think!_

**Comment by shotamatsuda** [comment]
No, this doesn’t work with an OrthographicCamera currently. I agree it would be great to support it, but it’s a low priority for now.
I don’t think there are any inherent limitations to implementing it. It will just need adding more conditions to handle the matrix and depth.

**Comment by gkjohnson** [comment]
> it’s a low priority for now.
> ...
> It will just need adding more conditions to handle the matrix and depth.

I figured it would be - but this is something I can take a look at when I have some time!

> It will just need adding more conditions to handle the matrix and depth.

What do you mean by this? Which depth and matrices specifically? [These calculations](https://github.com/takram-design-engineering/three-geospatial/blob/2f1dd0f30d1bd9247d04a6c0d9fd9ee361e82ff5/packages/atmosphere/src/shaders/sky.vert#L13-L17) in the vertex shader for the view parameters looked like the primary values that need to change.

**Comment by shotamatsuda** [comment]
Thanks! It would be very helpful.

>What do you mean by this? Which depth and matrices specifically? [These calculations](https://github.com/takram-design-engineering/three-geospatial/blob/2f1dd0f30d1bd9247d04a6c0d9fd9ee361e82ff5/packages/atmosphere/src/shaders/sky.vert#L13-L17) in the vertex shader for the view parameters looked like the primary values that need to change.

For the sky shaders, that’s correct. But in `AerialPerspectiveEffect`, we also need the world positions of texels (not hard, but I’m lazy enough to skip it). There're other functions like [`PointOfView`](https://github.com/takram-design-engineering/three-geospatial/blob/main/packages/core/src/PointOfView.ts), which casts ray from the camera.

**Comment by gkjohnson** [comment]
>  But in AerialPerspectiveEffect, we also need the world positions of texels (not hard, but I’m lazy enough to skip it)

What do you mean by this? It's possible I'm missing something in #15.
